In [1]:
import os
print(os.getcwd())

C:\Users\ASUS\Desktop\sentiment_analysis\notebooks

In [2]:
import json

In [3]:
with open("../artifacts/kaggle.json", "r") as file:
    data = json.load(file)

print(data)

{'username': 'cristianwebster', 'key': 'b7a62074e7f6ae621b56018bc0120207'}

In [4]:
python -m pip install kaggle

SyntaxError: invalid syntax (2988031630.py, line 1)

In [5]:
import sys
!{sys.executable} -m pip install kaggle

Collecting kaggle
  Downloading kaggle-2.0.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: bleach in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kaggle) (6.3.0)
Collecting kagglesdk<1.0,>=0.1.17 (from kaggle)
  Downloading kagglesdk-0.1.19-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kaggle) (26.1)
Collecting protobuf (from kaggle)
  Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: python-dateutil in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kaggle) (2.9.0.post0)
Collecting python-slugify (from kaggle)
  Downloading python_slugify-8.0.4-py2.py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: requests in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kaggle) (2.33.1)
Collecting tqdm (from kaggle)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: urllib3>=1.15.1 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kaggle) (2.6.3)
Requirement already satisfied: webencodings in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: six>=1.5 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil->kaggle) (1.17.0)
Collecting text-unidecode>=1.3 (from python-slugify->kaggle)
  Downloading text_unidecode-1.3-py2.py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kaggle) (2026.2.25)
Requirement already satisfied: colorama in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tqdm->kaggle) (0.4.6)
Downloading kaggle-2.0.1-py3-none-any.whl (76 kB)
Downloading kagglesdk-0.1.19-py3-none-any.whl (208 kB)
Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl (437 kB)
Downloading python_slugify-8.0.4-py2.py3-none-any.whl (10 kB)
Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: text-unidecode, tqdm, python-slugify, protobuf, kagglesdk, kaggle

   ------ --------------------------------- 1/6 [tqdm]
   ------ --------------------------------- 1/6 [tqdm]
   ------------- -------------------------- 2/6 [python-slugify]
   -------------------- ------------------- 3/6 [protobuf]
   -------------------- ------------------- 3/6 [protobuf]
   -------------------- ------------------- 3/6 [protobuf]
   -------------------------- ------------- 4/6 [kagglesdk]
   -------------------------- ------------- 4/6 [kagglesdk]
   -------------------------- ------------- 4/6 [kagglesdk]
   -------------------------- ------------- 4/6 [kagglesdk]
   -------------------------- ------------- 4/6 [kagglesdk]
   --------------------------------- ------ 5/6 [kaggle]
   --------------------------------- ------ 5/6 [kaggle]
   --------------------------------- ------ 5/6 [kaggle]
   ---------------------------------------- 6/6 [kaggle]

Successfully installed kaggle-2.0.1 kagglesdk-0.1.19 protobuf-7.34.1 python-slugify-8.0.4 text-unidecode-1.3 tqdm-4.67.3

  WARNING: The script tqdm.exe is installed in 'C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script slugify.exe is installed in 'C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script kaggle.exe is installed in 'C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [6]:
import os
os.environ['KAGGLE_USERNAME'] = data['username']
os.environ['KAGGLE_KEY'] = data['key']

In [7]:
from keggle.spi,keggle_api_extend import KaggleApi
api=KaggleApi()
api.authenticate()

SyntaxError: invalid syntax (383663950.py, line 1)

In [8]:
from keggle.api,keggle_api_extend import KaggleApi
api=KaggleApi()
api.authenticate()

SyntaxError: invalid syntax (183417007.py, line 1)

In [9]:
from kaggle.api.kaggle_api_extended import KaggleApi

api = KaggleApi()
api.authenticate()

print("Kaggle authenticated successfully!")

Kaggle authenticated successfully!

In [10]:
api.dataset_download_files('dineshpiyasamara/sentiment-analysis-dataset',path=../artifacts/ )

SyntaxError: invalid syntax (3141349288.py, line 1)

In [11]:
from kaggle.api.kaggle_api_extended import KaggleApi
import os

# create folder
os.makedirs("artifacts", exist_ok=True)

# authenticate
api = KaggleApi()
api.authenticate()

# download dataset
api.dataset_download_files(
    'dineshpiyasamara/sentiment-analysis-dataset',
    path="artifacts/",
    unzip=True
)

print("Download completed!")

Dataset URL: https://www.kaggle.com/datasets/dineshpiyasamara/sentiment-analysis-dataset
Download completed!

In [12]:
import zipfile
with zipfile.Zipfile('../artifacts/sentiment-analysis-dataset.zip','r')as zip_ref:
    zip_ref.extractall('../artifact/')

AttributeError: module 'zipfile' has no attribute 'Zipfile'

In [13]:
import zipfile

with zipfile.ZipFile('../artifacts/sentiment-analysis-dataset.zip', 'r') as zip_ref:
    zip_ref.extractall('../artifacts/')

print("Extraction done!")

FileNotFoundError: [Errno 2] No such file or directory: '../artifacts/sentiment-analysis-dataset.zip'

In [14]:
import zipfile

with zipfile.ZipFile('artifacts/sentiment-analysis-dataset.zip', 'r') as zip_ref:
    zip_ref.extractall('artifacts/')

print("Extraction done!")

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/sentiment-analysis-dataset.zip'

In [15]:
import os
print(os.path.exists("artifacts/sentiment-analysis-dataset.zip"))

False

In [16]:
import os

for root, dirs, files in os.walk("."):
    for file in files:
        if "zip" in file:
            print(os.path.join(root, file))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("All libraries imported successfully!")

In [2]:
data = pd.read_csv('../artifacts/sentiment_analysis.csv')

In [3]:
data.head()

   id  label                                              tweet
0   1      0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1   2      0  Finally a transparant silicon case ^^ Thanks t...
2   3      0  We love this! Would you go? #talk #makememorie...
3   4      0  I'm wired I know I'm George I was made that wa...
4   5      1  What amazing service! Apple won't even talk to...

In [4]:
## Data Preprocessing

## Data Preprocessing

In [5]:
data.shape

(7920, 3)

In [6]:
data.duplicated

<bound method DataFrame.duplicated of         id  label                                              tweet
0        1      0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1        2      0  Finally a transparant silicon case ^^ Thanks t...
2        3      0  We love this! Would you go? #talk #makememorie...
3        4      0  I'm wired I know I'm George I was made that wa...
4        5      1  What amazing service! Apple won't even talk to...
...    ...    ...                                                ...
7915  7916      0  Live out loud #lol #liveoutloud #selfie #smile...
7916  7917      0  We would like to wish you an amazing day! Make...
7917  7918      0  Helping my lovely 90 year old neighbor with he...
7918  7919      0  Finally got my #smart #pocket #wifi stay conne...
7919  7920      0  Apple Barcelona!!! #Apple #Store #BCN #Barcelo...

[7920 rows x 3 columns]>

In [7]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7915    False
7916    False
7917    False
7918    False
7919    False
Length: 7920, dtype: bool

In [8]:
data.duplicated().sum()

np.int64(0)

In [9]:
data.isnull().sum()

id       0
label    0
tweet    0
dtype: int64

Text Preprocessing

In [10]:
import re
import string

In [11]:
convert uppercase to lowercase

SyntaxError: invalid syntax (701323663.py, line 1)

In [12]:
import os
print(os.path.exists('artifacts/sentiment_analysis.csv'))

False

In [13]:
import os
print(os.listdir("artifacts"))

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts'

In [14]:
import os

for root, dirs, files in os.walk("artifacts"):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

In [15]:
data = pd.read_csv("artifacts/train.csv")  # change to your real file name
print(data.head())

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/train.csv'

In [16]:
import os
print(os.listdir("artifacts"))

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts'

In [17]:
import os
print(os.getcwd())

C:\Users\ASUS\Desktop\sentiment_analysis\notebooks

In [18]:
import re
import string

In [19]:
dataset["tweet"]=dataset["tweet"].apply(lambda x:)"".join(x.lower() for x in x.split())

SyntaxError: invalid syntax (3991285069.py, line 1)

In [20]:
dataset["tweet"] = dataset["tweet"].apply(lambda x: " ".join(word.lower() for word in x.split()))

NameError: name 'dataset' is not defined

In [21]:
data["tweet"] = data["tweet"].apply(lambda x: " ".join(word.lower() for word in x.split()))

In [22]:
data["tweet"].head(5)

0    #fingerprint #pregnancy test https://goo.gl/h1...
1    finally a transparant silicon case ^^ thanks t...
2    we love this! would you go? #talk #makememorie...
3    i'm wired i know i'm george i was made that wa...
4    what amazing service! apple won't even talk to...
Name: tweet, dtype: str

In [23]:
data["tweet"] = data["tweet"].apply(lambda x: " ".join(re.sub(r'^https?:\/\/.*[\r\n]*', '',x,flags=re.MULTILINE) for x in x.split()))

In [24]:
data["tweet"].head(5)

0    #fingerprint #pregnancy test  #android #apps #...
1    finally a transparant silicon case ^^ thanks t...
2    we love this! would you go? #talk #makememorie...
3    i'm wired i know i'm george i was made that wa...
4    what amazing service! apple won't even talk to...
Name: tweet, dtype: str

In [25]:
def remove_punctuations(text):
    for punction in string.punctuation:
        text = text.replace(punctuation,'')
        return text
        data["tweet"]=data["tweet"].apply(remove_punctuations)

In [26]:
def remove_punctuations(text):
    for punction in string.punctuation:
        text = text.replace(punctuation,'')
        return text
        data["tweet"]=data["tweet"].apply(remove_punctuations)

In [27]:
data["tweet"].head(5)

0    #fingerprint #pregnancy test  #android #apps #...
1    finally a transparant silicon case ^^ thanks t...
2    we love this! would you go? #talk #makememorie...
3    i'm wired i know i'm george i was made that wa...
4    what amazing service! apple won't even talk to...
Name: tweet, dtype: str

In [28]:
import string

data["tweet"] = data["tweet"].str.replace(f"[{string.punctuation}]", "", regex=True)

In [29]:
data["tweet"].head(5)

0    fingerprint pregnancy test  android apps beaut...
1    finally a transparant silicon case  thanks to ...
2    we love this would you go talk makememories un...
3    im wired i know im george i was made that way ...
4    what amazing service apple wont even talk to m...
Name: tweet, dtype: str

In [30]:
data["tweet"] = data["tweet"].str.replace(r"\d+", "", regex=True).str.replace(r"\s+", " ", regex=True).str.strip()

In [31]:
!pip install nltk

Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Collecting click (from nltk)
  Downloading click-8.3.2-py3-none-any.whl.metadata (2.6 kB)
Collecting joblib (from nltk)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.4.4-cp314-cp314-win_amd64.whl.metadata (41 kB)
Requirement already satisfied: tqdm in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------------- -------------------------- 0.5/1.6 MB 588.9 kB/s eta 0:00:02
   ------------- -------------------------- 0.5/1.6 MB 588.9 kB/s eta 0:00:02
   -------------------- ------------------- 0.8/1.6 MB 615.2 kB/s eta 0:00:02
   -------------------- ------------------- 0.8/1.6 MB 615.2 kB/s eta 0:00:02
   --------------------------- ------------ 1.0/1.6 MB 623.2 kB/s eta 0:00:01
   --------------------------- ------------ 1.0/1.6 MB 623.2 kB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 657.3 kB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 657.3 kB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 635.8 kB/s  0:00:02
Downloading regex-2026.4.4-cp314-cp314-win_amd64.whl (280 kB)
Downloading click-8.3.2-py3-none-any.whl (108 kB)
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Installing collected packages: regex, joblib, click, nltk

   ---------------------------------------- 0/4 [regex]
   ---------------------------------------- 0/4 [regex]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   ---------- ----------------------------- 1/4 [joblib]
   -------------------- ------------------- 2/4 [click]
   -------------------- ------------------- 2/4 [click]
   -------------------- ------------------- 2/4 [click]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ---------------------------------------- 4/4 [nltk]

Successfully installed click-8.3.2 joblib-1.5.3 nltk-3.9.4 regex-2026.4.4

  WARNING: The script nltk.exe is installed in 'C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [32]:
import nltk

In [1]:
nltk.download('stopwords',download_dir='../static/model')

NameError: name 'nltk' is not defined

In [2]:
import nltk

In [3]:
nltk.download('stopwords', download_dir='../static/model')

[nltk_data] Downloading package stopwords to ../static/model...
[nltk_data]   Unzipping corpora\stopwords.zip.
C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\nltk\downloader.py:2395: RuntimeWarning: Security Violation [pathsec.ZipFile]: Unauthorized path C:\Users\ASUS\Desktop\sentiment_analysis\static\model\corpora\stopwords.zip
  zf = ZipFile(filename)

True

In [4]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [5]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
print(list(stop_words)[:10])

["he'll", 'themselves', "haven't", 'mightn', 'myself', "hadn't", 'am', 'our', "won't", 'ourselves']

In [6]:
data["tweet"]=data["tweet"].aplly(lambda x:"".join(x for x in x.split() if x not in stop_words))

NameError: name 'data' is not defined

In [7]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

data["tweet"] = data["tweet"].apply(
    lambda x: " ".join(word for word in x.split() if word.lower() not in stop_words)
)

NameError: name 'data' is not defined

In [8]:
import pandas as pd

data = pd.read_excel("../artifacts/sentiment_analysis.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: '../artifacts/sentiment_analysis.xlsx'

In [9]:
import os
print(os.listdir("artifacts"))

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts'

In [10]:
import os
print(os.listdir("artifacts"))

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts'

In [11]:
import os
print(os.listdir("../artifacts"))

['kaggle.json', 'sentiment_analysis.csv']

In [12]:
import pandas as pd

data = pd.read_csv("artifacts/sentiment_analysis.csv")
print(data.head())

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/sentiment_analysis.csv'

In [13]:
data["tweet"]=data["tweet"].aplly(lambda x:"".join(x for x in x.split() if x not in stop_words))

NameError: name 'data' is not defined

In [14]:
data["tweet"].head(5)

NameError: name 'data' is not defined

In [15]:
data["tweet"].head(5)

NameError: name 'data' is not defined

In [16]:
nltk.download('stopwords',download_dir='../static/model')

[nltk_data] Downloading package stopwords to ../static/model...
[nltk_data]   Unzipping corpora\stopwords.zip.
C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\nltk\downloader.py:2395: RuntimeWarning: Security Violation [pathsec.ZipFile]: Unauthorized path C:\Users\ASUS\Desktop\sentiment_analysis\static\model\corpora\stopwords.zip
  zf = ZipFile(filename)

True

In [17]:
data["tweet"]=data["tweet"].aplly(lambda x:"".join(x for x in x.split() if x not in stop_words))

NameError: name 'data' is not defined

In [18]:
data["tweet"]=data["tweet"].aplly(lambda x:"".join(x for x in x.split() if x not in stop_words))

NameError: name 'data' is not defined

In [19]:
import pandas as pd

data = pd.read_csv("artifacts/sentiment_analysis.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/sentiment_analysis.csv'

In [20]:
import os
print(os.getcwd())

C:\Users\ASUS\Desktop\sentiment_analysis\notebooks

In [21]:
import pandas as pd

data = pd.read_csv("../artifacts/sentiment_analysis.csv")

In [22]:
import os
os.chdir(r"C:\Users\ASUS\Desktop\sentiment_analysis")

In [23]:
data = pd.read_csv("artifacts/sentiment_analysis.csv")

In [24]:
data["tweet"]=data["tweet"].aplly(lambda x:"".join(x for x in x.split() if x not in stop_words))

AttributeError: 'Series' object has no attribute 'aplly'

In [25]:
data["tweet"] = data["tweet"].apply(
    lambda x: " ".join(word for word in str(x).split() if word.lower() not in stop_words)
)

In [26]:
data["tweet"].head()

0    #fingerprint #Pregnancy Test https://goo.gl/h1...
1    Finally transparant silicon case ^^ Thanks unc...
2    love this! Would go? #talk #makememories #unpl...
3    wired know George made way ;) #iphone #cute #d...
4    amazing service! Apple even talk question unle...
Name: tweet, dtype: str

In [27]:
import re
import string
import pandas as pd
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [28]:
stop_words = set(stopwords.words("english"))
stemmer = PorterStemmer()

In [29]:
def clean_text(text):
    text = str(text)

    # lowercase
    text = text.lower()

    # remove links
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)

    # remove numbers
    text = re.sub(r"\d+", "", text)

    # remove punctuation
    text = text.translate(str.maketrans("", "", string.punctuation))

    # tokenize
    words = text.split()

    # remove stopwords + stemming
    words = [stemmer.stem(word) for word in words if word not in stop_words]

    return " ".join(words)

In [30]:
data["tweet"] = data["tweet"].apply(clean_text)

In [31]:
print(data.head())

   id  label                                              tweet
0   1      0  fingerprint pregnanc test android app beauti c...
1   2      0  final transpar silicon case thank uncl yay son...
2   3      0  love would go talk makememori unplug relax iph...
3   4      0  wire know georg made way iphon cute daventri home
4   5      1  amaz servic appl even talk question unless pay...

In [32]:
print(data.tail())

        id  label                                              tweet
7915  7916      0  live loud lol liveoutloud selfi smile soni mus...
7916  7917      0  would like wish amaz day make everi minut coun...
7917  7918      0  help love year old neighbor ipad morn made rea...
7918  7919      0  final got smart pocket wifi stay connect anyti...
7919  7920      0  appl barcelona appl store bcn barcelona travel...

In [33]:
data

        id  label                                              tweet
0        1      0  fingerprint pregnanc test android app beauti c...
1        2      0  final transpar silicon case thank uncl yay son...
2        3      0  love would go talk makememori unplug relax iph...
3        4      0  wire know georg made way iphon cute daventri home
4        5      1  amaz servic appl even talk question unless pay...
...    ...    ...                                                ...
7915  7916      0  live loud lol liveoutloud selfi smile soni mus...
7916  7917      0  would like wish amaz day make everi minut coun...
7917  7918      0  help love year old neighbor ipad morn made rea...
7918  7919      0  final got smart pocket wifi stay connect anyti...
7919  7920      0  appl barcelona appl store bcn barcelona travel...

[7920 rows x 3 columns]

In [34]:
from collections import Counter 
volab = Counter()

In [35]:
vocab

NameError: name 'vocab' is not defined

In [36]:
from collections import Counter

In [37]:
vocab = Counter()

In [38]:
for text in data["tweet"]:
    vocab.update(text.split())

In [39]:
print(vocab.most_common(10))

[('iphon', 4073), ('appl', 2876), ('samsung', 1395), ('new', 1137), ('phone', 1015), ('follow', 885), ('soni', 819), ('…', 756), ('ipad', 537), ('rt', 525)]

In [40]:
len(vocab)

15883

In [41]:
data.shape

(7920, 3)

In [42]:
tokens=[key for key in vocab if vocab [key]>10]

In [43]:
tokens

['test',
 'android',
 'app',
 'beauti',
 'cute',
 'health',
 'iger',
 'iphoneonli',
 'iphonesia',
 'iphon',
 'final',
 'case',
 'thank',
 'yay',
 'soni',
 'xperia',
 'love',
 'would',
 'go',
 'talk',
 'relax',
 'smartphon',
 'wifi',
 'connect',
 'know',
 'made',
 'way',
 'home',
 'amaz',
 'servic',
 'appl',
 'even',
 'question',
 'pay',
 'stupid',
 'support',
 'softwar',
 'updat',
 'fuck',
 'phone',
 'big',
 'time',
 'happi',
 'us',
 'instap',
 'instadaili',
 'xperiaz',
 'new',
 'type',
 'c',
 'charger',
 'cabl',
 'uk',
 '…',
 'amazon',
 'year',
 'newyear',
 'start',
 'technolog',
 'samsunggalaxi',
 'iphonex',
 'shop',
 'listen',
 'music',
 'likeforlik',
 'photo',
 'fun',
 'selfi',
 'water',
 'camera',
 'picoftheday',
 'sun',
 'instagood',
 'boy',
 'outdoor',
 'hey',
 'make',
 'ipod',
 'dont',
 'color',
 'inch',
 'crash',
 'everi',
 'need',
 'realli',
 'drop',
 'ball',
 'design',
 'give',
 'anoth',
 'crazi',
 'purchas',
 'lol',
 'work',
 'hard',
 'play',
 'ipad',
 'batteri',
 'charg',
 'dead',
 'saturday',
 'summer',
 'like',
 'share',
 'want',
 'instagram',
 'photooftheday',
 'tweegram',
 'reason',
 'one',
 'suck',
 'truth',
 'agre',
 'fact',
 'store',
 'screen',
 'monday',
 'ur',
 'art',
 'easter',
 'dear',
 'friend',
 'face',
 'email',
 'seem',
 'pie',
 'wife',
 'day',
 'button',
 'back',
 'broke',
 'hit',
 'goe',
 'complet',
 'black',
 'keep',
 'get',
 'text',
 'cant',
 'check',
 'wallpap',
 'wall',
 'galaxi',
 'samsung',
 'patent',
 'million',
 'parti',
 'mess',
 'done',
 'noth',
 'touch',
 'lose',
 'pic',
 'kill',
 'someon',
 'hateappl',
 'flower',
 'green',
 'must',
 'watch',
 'youtub',
 'subscrib',
 'daili',
 'vlog',
 'twitch',
 'game',
 'ps',
 'xbox',
 'io',
 'live',
 'laugh',
 'life',
 'food',
 'instago',
 'instahub',
 'instagram…',
 'friendship',
 'dog',
 'famili',
 'goal',
 'bestfriend',
 'america',
 'taken',
 'sunset',
 'sky',
 'sister',
 'bought',
 'earli',
 'bday',
 'gift',
 'receiv',
 'note',
 'mani',
 'market',
 'delet',
 'song',
 'itun',
 'freak',
 'window',
 'advanc',
 'custom',
 'stand',
 'bad',
 'cheap',
 'tech',
 'bull',
 'smile',
 'creat',
 'let',
 'sunday',
 'alway',
 'eye',
 'ootd',
 'fashion',
 'blackandwhit',
 'film',
 'set',
 'video',
 'produc',
 'follow',
 'movi',
 'act',
 'pink',
 'sweet',
 'sexi',
 'ladi',
 'week',
 'end',
 'iphoneplu',
 'moment',
 'see',
 'differ',
 'photographi',
 'natur',
 'landscap',
 'view',
 'tree',
 'travel',
 'googl',
 'cut',
 'program',
 'look',
 'got',
 'christma',
 'girl',
 'instacool',
 'free',
 'appstor',
 'joy',
 'peac',
 'reflect',
 'rememb',
 'cloud',
 'gr',
 'iphone…',
 'babi',
 'pet',
 'news',
 'fail',
 'funni',
 'hate',
 'tablet',
 'person',
 'use',
 'im',
 'fan',
 'think',
 'product',
 'friday',
 'call',
 'blackfriday',
 'holiday',
 'newyork',
 'busi',
 'money',
 'birthday',
 'tv',
 'comput',
 'school',
 'serious',
 'month',
 'good',
 'job',
 'actual',
 '£',
 'replac',
 'that',
 'still',
 'rt',
 'droid',
 'cool',
 'pictur',
 'l',
 'run',
 'beach',
 'sport',
 'bit',
 'hashtag',
 'yet',
 'arriv',
 'gain',
 'everyon',
 'sougofollow',
 'ff',
 'iphoneographi',
 'iphonephotographi',
 'mobil',
 'bright',
 'user',
 'date',
 'less',
 'random',
 'instamood',
 'wine',
 'creativ',
 'hot',
 'icon',
 'origin',
 'pop',
 'red',
 'rock',
 'soul',
 'singer',
 'univers',
 'wed',
 'thought',
 'lost',
 'ipadmini',
 'feel',
 'broken',
 'light',
 'pleas',
 'indonesia',
 'gold',
 'potd',
 'reset',
 'sorri',
 'white',
 'tea',
 'chill',
 'cover',
 'g',
 'came',
 'magic',
 'come',
 'followsunday',
 'followback',
 'teamfollowback',
 'retweet',
 'ya',
 'thing',
 'i’m',
 'it’',
 'alreadi',
 'problem',
 'issu',
 'abl',
 'sonya',
 'shoot',
 'put',
 'price',
 'devic',
 'win',
 'box',
 'memori',
 'brother',
 '–',
 'oh',
 'lip',
 'enjoy',
 'playstat',
 'gamer',
 'someth',
 'wrong',
 'right',
 'today',
 'earphon',
 'lifestyl',
 'fuckyou',
 'never',
 'bug',
 'littl',
 'qualiti',
 'girlfriend',
 'card',
 'z',
 'present',
 'mom',
 'macbookpro',
 'macbook',
 'quot',
 'word',
 'tweetgram',
 'great',
 'repair',
 'hour',
 'everyth',
 'mode',
 'usa',
 'compani',
 'model',
 'cd',
 'featur',
 'coffe',
 'effect',
 'spring',
 'galaxynot',
 'special',
 'valentin',
 'nowplay',
 'daughter',
 'poem',
 'car',
 'sign',
 'lunch',
 'park',
 'banana',
 'autumn',
 'spend',
 'much',
 'book',
 'say',
 'u',
 'took',
 'download',
 'ad',
 'twitter',
 'educ',
 'n',
 'miss',
 'last',
 'min',
 'tmobil',
 'rid',
 'absolut',
 'annoy',
 'level',
 'buy',
 'full',
 'version',
 'import',
 'mood',
 'blog',
 'style',
 'bestoftheday',
 'pretti',
 'babe',
 'send',
 'turn',
 'imessag',
 'sleep',
 'popular',
 'tweet',
 'shotoniphon',
 'photograph',
 'sync',
 'second',
 'fml',
 'candi',
 'nice',
 'wait',
 'hand',
 'gb',
 'first',
 'bar',
 'key',
 'long',
 'cold',
 'boot',
 'siri',
 'doesnt',
 'liter',
 'cri',
 'contact',
 'wonder',
 'avail',
 'b',
 'laptop',
 'vaio',
 'blackberri',
 'best',
 'fruit',
 'fall',
 'soon',
 'yum',
 'mac',
 'display',
 'told',
 'stop',
 'p',
 'three',
 'ship',
 'gear',
 'well',
 'past',
 'singl',
 'capetownsup',
 'sup',
 'surf',
 'capetown',
 'pro',
 'half',
 'stuff',
 'excit',
 'open',
 'mine',
 'piss',
 'offici',
 'keyboard',
 'okay',
 'though',
 'enough',
 'simpl',
 'th',
 'refus',
 'night',
 'son',
 'instagood…',
 'jj',
 'makeup',
 'valentinesday',
 'februari',
 'portrait',
 'shot',
 'sonyalpha',
 'mm',
 'password',
 'zoom',
 'stevejob',
 'yall',
 'addict',
 'prophet',
 'husband',
 'kindl',
 'a…',
 'upgrad',
 'help',
 'children',
 'there',
 'least',
 'tab',
 'real',
 'visit',
 'hi',
 'world',
 'old',
 'followm',
 'likelik',
 'samsung…',
 'swag',
 'cat',
 'edit',
 'sick',
 'paint',
 'bullshit',
 'may',
 'perfect',
 'instaphoto',
 'welcom',
 'draw',
 'os',
 'throw',
 'fast',
 'w',
 'take',
 'two',
 'next',
 'offer',
 'middl',
 'access',
 'account',
 'find',
 'citi',
 'stori',
 'destini',
 'awesom',
 'accessori',
 'info',
 'goodnight',
 'dream',
 'hope',
 'uae',
 'lucki',
 'deal',
 'passion',
 'read',
 'edm',
 'whole',
 'playlist',
 'god',
 'nx',
 'cuti',
 'high',
 'usb',
 'geek',
 'bot',
 'gadget',
 'power',
 'pc',
 'sprint',
 'pick',
 'wish',
 'minut',
 'count',
 'tl',
 'drive',
 'nyc',
 'gay',
 'readi',
 'cellphon',
 'space',
 'ny',
 'tattoo',
 'id',
 'total',
 'ye',
 'via',
 'air',
 'instal',
 'fit',
 'plu',
 'sim',
 'florida',
 'sale',
 'nokia',
 'motorola',
 'lg',
 'without',
 'hold',
 'speed',
 'unitedst',
 'guitarplay',
 'smart',
 'crap',
 'calendar',
 'event',
 'icloud',
 'angri',
 'bird',
 'freez',
 'ever',
 'sinc',
 'team',
 'tri',
 'convers',
 'small',
 'blue',
 '—',
 'steemit',
 'sonylen',
 'len',
 'sonyphotographi',
 'imag',
 'photofe',
 'feed',
 'yeah',
 'gorgeou',
 'ig',
 'orang',
 'haha',
 'dress',
 'lock',
 'speaker',
 'reallyr',
 'colleg',
 'true',
 'chocol',
 'shit',
 'ador',
 'nofilt',
 'drink',
 'purpl',
 'tasti',
 'garden',
 'андроид',
 'guy',
 'bestpric',
 'jun',
 'unlock',
 'caus',
 'manag',
 'mommi',
 'bless',
 'could',
 'chines',
 'close',
 'system',
 'morn',
 'nike',
 'goodmorn',
 'r',
 'imac',
 'sell',
 'mad',
 'purpos',
 'pari',
 'answer',
 'roll',
 'verizon',
 'headphon',
 'show',
 'sound',
 'itali',
 'socialmedia',
 'learn',
 'smoke',
 'tomorrow',
 'here',
 'delici',
 'far',
 'away',
 'ebay',
 'fix',
 'easi',
 'silver',
 'oneplu',
 'provid',
 'experi',
 'flag',
 'emoji',
 'chang',
 'al',
 'april',
 'man',
 'wanna',
 'tell',
 'kid',
 'backup',
 'peopl',
 'dad',
 'anyon',
 'els',
 'block',
 'number',
 'possibl',
 'frustrat',
 'file',
 'bro',
 'rhyme',
 'thx',
 'jailbreak',
 'sit',
 'restor',
 'stock',
 'mother',
 'igdaili',
 'marri',
 'healthi',
 'ugh',
 'x',
 'bc',
 'gratitud',
 'edg',
 'unbox',
 'wow',
 'sonyphoto',
 'top',
 'danc',
 'phonecas',
 'june',
 'sad',
 'yellow',
 'woman',
 'might',
 'india',
 'canada',
 'europ',
 'super',
 'care',
 'map',
 'applestor',
 'hello',
 'order',
 'sent',
 'went',
 'insta',
 'newphon',
 'fish',
 'london',
 'vsco',
 'track',
 'catch',
 'finger',
 'anymor',
 'captur',
 'futur',
 'cell',
 'instalik',
 'sony…',
 'march',
 'proud',
 'hateiphon',
 'sticker',
 'vscocam',
 'bring',
 'better',
 'kiss',
 'heart',
 'fresh',
 'librari',
 'inspir',
 'inlov',
 'luxuri',
 'exquisit',
 'squishi',
 'charm',
 'strap',
 'toy',
 'decor',
 'cake',
 'lte',
 'facebook',
 'wipe',
 'human',
 'bff',
 'instalov',
 'storag',
 'wake',
 'shitti',
 'wast',
 'switch',
 'blond',
 'load',
 'sue',
 'teamandroid',
 'da',
 'ly',
 'lion',
 'steve',
 'also',
 'osx',
 'photoshoot',
 'coupl',
 'favorit',
 'forc',
 'newtoy',
 'nascar',
 'tire',
 'appar',
 'ago',
 'zeeland',
 'appletv',
 'ask',
 'said',
 'meet',
 'electron',
 'gener',
 'link',
 'code',
 'tshirt',
 'tbt',
 'beat',
 'screw',
 'videogam',
 'motiv',
 'sunni',
 'nikon',
 'useless',
 'boyfriend',
 'weekend',
 'cook',
 'japan',
 'starbuck',
 'almost',
 'cousin',
 'tag',
 'applesuck',
 'everyday',
 'bye',
 'search',
 'dinner',
 'discount',
 'cheer',
 'bluetooth',
 'wireless',
 'data',
 'spent',
 'wont',
 'puppi',
 'vacat',
 'anim',
 'notebook',
 'redbubbl',
 'iphonecas',
 'king',
 'yo',
 'left',
 'mean',
 'what',
 'yesterday',
 'mayb',
 'trump',
 'california',
 'repost',
 'samsungmobil',
 'gone',
 'social',
 'break',
 'trip',
 'slow',
 'rain',
 'wtf',
 'anyth',
 'cuz',
 'hd',
 'microsoft',
 'applewatch',
 'duo',
 'dj',
 'save',
 'mr',
 'releas',
 'gonna',
 'entir',
 'part',
 'die',
 'k',
 'tip',
 'gotta',
 'eat',
 'walk',
 'side',
 'explor',
 'hous',
 'room',
 'rs',
 'piano',
 'v',
 'thankyou',
 'happen',
 'page',
 'surpris',
 'deliveri',
 'messag',
 'vocat',
 'thailand',
 'khaoko',
 'ilc',
 'snapspeed…',
 'merri',
 'htc',
 'onlin',
 'psn',
 'flash',
 '•',
 'treat',
 'tagsforlik',
 'cost',
 'crack',
 'collect',
 'stuck',
 'planet',
 'men',
 'followfollow',
 'blow',
 'latest',
 'consol',
 'blogger',
 'protect',
 'skin',
 'choos',
 'uniqu',
 'piec',
 'lot',
 'remov',
 'secur',
 'princess',
 'mind',
 'becom',
 'miami',
 'nail',
 'rip',
 'figur',
 'network',
 'bitch',
 'tuesday',
 'f',
 'idea',
 'fb',
 'omg',
 'innov',
 'player',
 'forev',
 'satisfi',
 'tonight',
 'artist',
 'sing',
 'click',
 'hair',
 'ride',
 'leav',
 'colour',
 'togeth',
 'asshol',
 'hack',
 'post',
 'till',
 'wors',
 'voic',
 'att',
 ...]

In [44]:
len(vocab)

15883

In [45]:
def save_vocabulary (lines, filename):
    data = '\n'.join (lines)
    file = open(filename, 'w', encoding="utf-8")
    file.write(data)
    file.close()

    save_vocabulary(tokens, '../static/model/vocabulary.txt')

In [46]:
tokens = list(vocab.keys())

def save_vocabulary(lines, filename):
    data = "\n".join(lines)
    with open(filename, "w", encoding="utf-8") as file:
        file.write(data)

save_vocabulary(tokens, "../static/model/vocabulary.txt")

FileNotFoundError: [Errno 2] No such file or directory: '../static/model/vocabulary.txt'

In [47]:
import os

os.makedirs("../static/model", exist_ok=True)

def save_vocabulary(lines, filename):
    data = "\n".join(lines)
    with open(filename, "w", encoding="utf-8") as file:
        file.write(data)

save_vocabulary(tokens, "../static/model/vocabulary.txt")

In [48]:
BASE_DIR = "C:/Users/ASUS/Desktop/sentiment_analysis"
os.makedirs(f"{BASE_DIR}/static/model", exist_ok=True)

In [49]:
import os

print(os.path.exists("../static/model/vocabulary.txt"))

True

In [50]:
import os

for root, dirs, files in os.walk(".."):
    for file in files:
        if "vocabulary" in file:
            print(os.path.join(root, file))

..\static\model\vocabulary.txt

In [1]:
def save_vocabulary(lines, filename):
    data='\n'.join(lines)
    file=open(filename, 'w', encoding="utf-8")
    file.write(data)
    file.close()
save_vocabulary(tokens, '../static/model/vocabulary.txt')

NameError: name 'tokens' is not defined

In [2]:
tokens = list(vocab.keys())

NameError: name 'vocab' is not defined

In [3]:
from collections import Counter

vocab = Counter()

for text in data["tweet"]:
    vocab.update(str(text).split())

tokens = list(vocab.keys())

NameError: name 'data' is not defined

In [4]:
def save_vocabulary(lines, filename):
    data='\n'.join(lines)
    file=open(filename, 'w', encoding="utf-8")
    file.write(data)
    file.close()
save_vocabulary(tokens, 'static/model/vocabulary.txt')

NameError: name 'tokens' is not defined

In [5]:
import pandas as pd
data = pd.read_csv("../artifacts/sentiment_analysis.csv")

In [6]:
from collections import Counter

vocab = Counter()

for text in data["tweet"]:
    vocab.update(str(text).split())

In [7]:
tokens = list(vocab.keys())

In [8]:
print(len(tokens))
print(tokens[:10])

34348
['#fingerprint', '#Pregnancy', 'Test', 'https://goo.gl/h1MfQV', '#android', '#apps', '#beautiful', '#cute', '#health', '#igers']

In [9]:
import re
import string
import pandas as pd
import nltk

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [10]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [11]:
stop_words = set(stopwords.words("english"))
stemmer = PorterStemmer()

In [12]:
def preprocess_text(text):
    text = str(text)

    # 1. lowercase
    text = text.lower()

    # 2. remove links
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)

    # 3. remove numbers
    text = re.sub(r"\d+", "", text)

    # 4. remove punctuation
    text = text.translate(str.maketrans("", "", string.punctuation))

    # 5. tokenize
    words = text.split()

    # 6. remove stopwords + stemming
    words = [stemmer.stem(word) for word in words if word not in stop_words]

    return words   # return tokens (list)

In [13]:
data["tokens"] = data["tweet"].apply(preprocess_text)

In [14]:
print(data[["tweet", "tokens"]].head())

                                               tweet  \
0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1  Finally a transparant silicon case ^^ Thanks t...
2  We love this! Would you go? #talk #makememorie...
3  I'm wired I know I'm George I was made that wa...
4  What amazing service! Apple won't even talk to...

                                              tokens
0  [fingerprint, pregnanc, test, android, app, be...
1  [final, transpar, silicon, case, thank, uncl, ...
2  [love, would, go, talk, makememori, unplug, re...
3  [im, wire, know, im, georg, made, way, iphon, ...
4  [amaz, servic, appl, wont, even, talk, questio...

In [15]:
import os
os.makedirs("static/model", exist_ok=True)

In [16]:
def save_vocabulary(lines, filename):
    data = "\n".join(lines)
    with open(filename, "w", encoding="utf-8") as file:
        file.write(data)

save_vocabulary(tokens, "static/model/vocabulary.txt")

In [17]:
print("tokens" in globals())

True

In [18]:
save_vocabulary(tokens, "../static/model/vocabulary.txt")

In [19]:
import os
print(os.path.exists("../static/model/vocabulary.txt"))

True

In [20]:
X=data['tweet']
y=data['label']

In [21]:
from sklearn.model_selection impoert train_test_split
X_train, y_train, X_test, y_test=train_test_split(X,y,test_split=0.2)

SyntaxError: invalid syntax (605046755.py, line 1)

In [22]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.4.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.5.3)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 5.8 MB/s eta 0:00:02
   --------- ------------------------------ 1.8/8.1 MB 6.1 MB/s eta 0:00:02
   --------------- ------------------------ 3.1/8.1 MB 6.1 MB/s eta 0:00:01
   ---------------------- ----------------- 4.5/8.1 MB 6.0 MB/s eta 0:00:01
   ---------------------------- ----------- 5.8/8.1 MB 6.1 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.1 MB 6.1 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 6.2 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 5.6 MB/s  0:00:01
Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   - -------------------------------------- 1.0/37.3 MB 6.3 MB/s eta 0:00:06
   -- ------------------------------------- 2.6/37.3 MB 6.7 MB/s eta 0:00:06
   ---- ----------------------------------- 3.9/37.3 MB 6.7 MB/s eta 0:00:05
   ----- ---------------------------------- 5.5/37.3 MB 6.7 MB/s eta 0:00:05
   ------- -------------------------------- 6.8/37.3 MB 6.8 MB/s eta 0:00:05
   -------- ------------------------------- 8.4/37.3 MB 6.8 MB/s eta 0:00:05
   --------- ------------------------------ 8.7/37.3 MB 6.8 MB/s eta 0:00:05
   ----------- ---------------------------- 10.7/37.3 MB 6.7 MB/s eta 0:00:04
   ------------ --------------------------- 12.1/37.3 MB 6.5 MB/s eta 0:00:04
   ------------- -------------------------- 12.8/37.3 MB 6.4 MB/s eta 0:00:04
   -------------- ------------------------- 13.9/37.3 MB 6.1 MB/s eta 0:00:04
   --------------- ------------------------ 14.7/37.3 MB 6.1 MB/s eta 0:00:04
   ----------------- ---------------------- 16.0/37.3 MB 6.0 MB/s eta 0:00:04
   ------------------ --------------------- 17.0/37.3 MB 5.9 MB/s eta 0:00:04
   ------------------- -------------------- 18.1/37.3 MB 5.8 MB/s eta 0:00:04
   -------------------- ------------------- 19.1/37.3 MB 5.8 MB/s eta 0:00:04
   ---------------------- ----------------- 20.7/37.3 MB 5.8 MB/s eta 0:00:03
   ----------------------- ---------------- 22.0/37.3 MB 5.9 MB/s eta 0:00:03
   ------------------------- -------------- 23.6/37.3 MB 6.0 MB/s eta 0:00:03
   -------------------------- ------------- 24.9/37.3 MB 6.0 MB/s eta 0:00:03
   ---------------------------- ----------- 26.5/37.3 MB 6.1 MB/s eta 0:00:02
   ----------------------------- ---------- 27.8/37.3 MB 6.1 MB/s eta 0:00:02
   ------------------------------- -------- 29.4/37.3 MB 6.2 MB/s eta 0:00:02
   --------------------------------- ------ 30.9/37.3 MB 6.2 MB/s eta 0:00:02
   ---------------------------------- ----- 32.2/37.3 MB 6.2 MB/s eta 0:00:01
   ----------------------------------- ---- 33.3/37.3 MB 6.2 MB/s eta 0:00:01
   ------------------------------------- -- 34.6/37.3 MB 6.2 MB/s eta 0:00:01
   -------------------------------------- - 35.7/37.3 MB 6.2 MB/s eta 0:00:01
   ---------------------------------------  36.4/37.3 MB 6.1 MB/s eta 0:00:01
   ---------------------------------------  37.0/37.3 MB 6.0 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.3 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.3 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 5.6 MB/s  0:00:06
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, scikit-learn

   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]

In [23]:
from sklearn.model_selection import train_test_split

X = data['tweet']
y = data['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
X_train.shape

(6336,)

In [25]:
X_test.shape

(1584,)

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [27]:
vectorizer(X_train_vec,tokens)

TypeError: 'TfidfVectorizer' object is not callable

In [28]:
vectorizer(X_train,tokens)

TypeError: 'TfidfVectorizer' object is not callable

In [29]:
X_train_vec

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 110072 stored elements and shape (6336, 19704)>

In [30]:
import numpy as np

def vectorizer(ds, vocabulary):
    vectorized_lst = []

    for sentence in ds:
        sentence_lst = np.zeros(len(vocabulary))

        words = sentence.split()

        for i in range(len(vocabulary)):
            if vocabulary[i] in words:
                sentence_lst[i] = 1

        vectorized_lst.append(sentence_lst)

    vectorized_lst_new = np.asarray(vectorized_lst, dtype=np.float32)

    return vectorized_lst_new

In [31]:
vectoried_x_train = vecrorizer(X_train,tokens)

NameError: name 'vecrorizer' is not defined

In [32]:
vectorized_X_train = vectorizer(X_train, tokens)

In [34]:
vectorized_X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(6336, 34348), dtype=float32)

In [35]:
import numpy as np

def vectorizer(ds, vocabulary):
    vectorized_lst = []

    for text in ds:
        sentence_lst = np.zeros(len(vocabulary))

        words = text.split()

        for i in range(len(vocabulary)):
            if vocabulary[i] in words:
                sentence_lst[i] = 1

        vectorized_lst.append(sentence_lst)

    vectorized_lst_new = np.asarray(vectorized_lst, dtype=np.float32)

    return vectorized_lst_new

In [36]:
import numpy as np

def vectorizer(ds, vocabulary):
    vectorized_lst = []

    for sentence in ds:
        sentence_lst = np.zeros(len(vocabulary))

        words = sentence.split()

        for i in range(len(vocabulary)):
            if vocabulary[i] in words:
                sentence_lst[i] = 1

        vectorized_lst.append(sentence_lst)

    vectorized_lst_new = np.asarray(vectorized_lst, dtype=np.float32)

    return vectorized_lst_new

In [37]:
for i in vectorized_x_train[0]:
    print(i)

NameError: name 'vectorized_x_train' is not defined

In [38]:
vectorized_X_train = vectorizer(X_train, tokens)

In [39]:
for i in vectorized_x_train[0]:
    print(i)

NameError: name 'vectorized_x_train' is not defined

In [ ]:
vectorized_X_test = vectorizer(X_test, tokens)

In [ ]:
y_test

In [40]:
import numpy as np

def vectorizer(ds, vocabulary):
    vectorized_lst = []

    for sentence in ds:
        sentence_lst = np.zeros(len(vocabulary))
        words = set(str(sentence).split())

        for i, word in enumerate(vocabulary):
            if word in words:
                sentence_lst[i] = 1

        vectorized_lst.append(sentence_lst)

    return np.array(vectorized_lst, dtype=np.float32)

In [41]:
tokens = list(vocab.keys())

In [42]:
X = data['tweet']
y = data['label']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [43]:
vectorized_X_train = vectorizer(X_train, tokens)

In [44]:
for i in vectorized_X_train[0]:
    print(i)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

In [45]:
y_test

5775    0
5259    1
1364    1
1336    0
5342    0
       ..
4716    0
4865    0
2060    0
1907    1
1680    1
Name: label, Length: 1584, dtype: int64

In [46]:
y_train.value_counts()

label
0    4715
1    1621
Name: count, dtype: int64

In [47]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
vectorized_x_train_smote, y_train_smote = smote.fit_resample(vectorized_x_train, y_train)
print(vectorized_x_train_smote.shape, y_train_smote.shape)

ModuleNotFoundError: No module named 'imblearn'

In [48]:
!pip install imbalanced-learn

Collecting imbalanced-learn
  Downloading imbalanced_learn-0.14.1-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: numpy<3,>=1.25.2 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from imbalanced-learn) (2.4.4)
Requirement already satisfied: scipy<2,>=1.11.4 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from imbalanced-learn) (1.17.1)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from imbalanced-learn) (1.8.0)
Collecting sklearn-compat<0.2,>=0.1.5 (from imbalanced-learn)
  Downloading sklearn_compat-0.1.5-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: joblib<2,>=1.2.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in C:\Users\ASUS\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from imbalanced-learn) (3.6.0)
Downloading imbalanced_learn-0.14.1-py3-none-any.whl (235 kB)
Downloading sklearn_compat-0.1.5-py3-none-any.whl (20 kB)
Installing collected packages: sklearn-compat, imbalanced-learn

   ---------------------------------------- 0/2 [sklearn-compat]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   -------------------- ------------------- 1/2 [imbalanced-learn]
   ---------------------------------------- 2/2 [imbalanced-learn]

Successfully installed imbalanced-learn-0.14.1 sklearn-compat-0.1.5

In [49]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
vectorized_x_train_smote, y_train_smote = smote.fit_resample(vectorized_x_train, y_train)
print(vectorized_x_train_smote.shape, y_train_smote.shape)

NameError: name 'vectorized_x_train' is not defined

In [50]:
smote = SMOTE()
vectorized_x_train_smote, y_train_smote = smote.fit_resample(
    vectorized_x_train, 
    y_train
)

NameError: name 'vectorized_x_train' is not defined

In [51]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

vectorized_x_train = vectorizer.fit_transform(X_train)
vectorized_x_test = vectorizer.transform(X_test)

In [52]:
from imblearn.over_sampling import SMOTE

smote = SMOTE()
X_train_smote, y_train_smote = smote.fit_resample(
    vectorized_x_train,
    y_train
)

In [53]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(class_weight='balanced')

In [54]:
print(vectorized_x_train.shape)
print(len(y_train))

(6336, 19459)
6336

In [55]:
y_train_smote.value_counts()

label
0    4715
1    4715
Name: count, dtype: int64

In [56]:
vectorized_x_train_smote

NameError: name 'vectorized_x_train_smote' is not defined

In [57]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

vectorized_x_train = vectorizer.fit_transform(X_train)
vectorized_x_test = vectorizer.transform(X_test)

In [58]:
print(vectorized_x_train_smote.shape)

NameError: name 'vectorized_x_train_smote' is not defined

In [59]:
from imblearn.over_sampling import SMOTE

smote = SMOTE()

vectorized_x_train_smote, y_train_smote = smote.fit_resample(
    vectorized_x_train,
    y_train
)

In [60]:
print(vectorized_x_train_smote.shape)

(9430, 19459)

In [61]:
vectorized_x_train_smote

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 194646 stored elements and shape (9430, 19459)>

In [62]:
print(vectorized_x_train_smote[0].toarray())

[[0. 0. 0. ... 0. 0. 0.]]

In [63]:
y_train_smote

0       0
1       1
2       0
3       0
4       0
       ..
9425    1
9426    1
9427    1
9428    1
9429    1
Name: label, Length: 9430, dtype: int64

In [64]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [65]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

def training_scores(y_act, y_pred):
    acc = round(accuracy_score(y_act, y_pred), 3)
    pr = round(precision_score(y_act, y_pred), 3)
    rec = round(recall_score(y_act, y_pred), 3)
    f1 = round(f1_score(y_act, y_pred), 3)

    print(f'Training Scores:\n\tAccuracy = {acc}\n\tPrecision = {pr}\n\tRecall = {rec}\n\tF1-Score = {f1}')


def validation_scores(y_act, y_pred):
    acc = round(accuracy_score(y_act, y_pred), 3)
    pr = round(precision_score(y_act, y_pred), 3)
    rec = round(recall_score(y_act, y_pred), 3)
    f1 = round(f1_score(y_act, y_pred), 3)

    print(f'Validation Scores:\n\tAccuracy = {acc}\n\tPrecision = {pr}\n\tRecall = {rec}\n\tF1-Score = {f1}')

In [75]:
lr.LogisticRegression()
lr.fit(vectorized_x_train_smote, y_train_smote)
y_train_pred = lr.predict(vectorized_x_train_smote)
y_test_pred = lr.predict(vectorized_x_test)
training_scores(y_train_smote, y_train_pred)
validation_scores(y_test, y_test_pred)

AttributeError: 'LogisticRegression' object has no attribute 'LogisticRegression'

In [76]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)

lr.fit(vectorized_x_train_smote, y_train_smote)

y_train_pred = lr.predict(vectorized_x_train_smote)
y_test_pred = lr.predict(vectorized_x_test)

training_scores(y_train_smote, y_train_pred)
validation_scores(y_test, y_test_pred)

Training Scores:
	Accuracy = 0.947
	Precision = 0.925
	Recall = 0.974
	F1-Score = 0.949
Validation Scores:
	Accuracy = 0.896
	Precision = 0.751
	Recall = 0.891
	F1-Score = 0.815

In [77]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()

nb.fit(vectorized_x_train, y_train)

y_train_pred = nb.predict(vectorized_x_train)
y_test_pred = nb.predict(vectorized_x_test)

training_scores(y_train, y_train_pred)
validation_scores(y_test, y_test_pred)

Training Scores:
	Accuracy = 0.927
	Precision = 0.925
	Recall = 0.778
	F1-Score = 0.845
Validation Scores:
	Accuracy = 0.859
	Precision = 0.864
	Recall = 0.533
	F1-Score = 0.66

In [78]:
 from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()

dt.fit(vectorized_x_train_smote, y_train_smote)

y_train_pred = dt.predict(vectorized_x_train_smote)
y_test_pred = dt.predict(vectorized_x_test)

training_scores(y_train_smote, y_train_pred)
validation_scores(y_test, y_test_pred)

IndentationError: unexpected indent (2596595132.py, line 1)

In [79]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()

dt.fit(vectorized_x_train_smote, y_train_smote)

y_train_pred = dt.predict(vectorized_x_train_smote)
y_test_pred = dt.predict(vectorized_x_test)

training_scores(y_train_smote, y_train_pred)
validation_scores(y_test, y_test_pred)

Training Scores:
	Accuracy = 1.0
	Precision = 1.0
	Recall = 1.0
	F1-Score = 1.0
Validation Scores:
	Accuracy = 0.844
	Precision = 0.687
	Recall = 0.716
	F1-Score = 0.701

In [80]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

rf.fit(vectorized_x_train_smote, y_train_smote)

y_train_pred = rf.predict(vectorized_x_train_smote)
y_test_pred = rf.predict(vectorized_x_test)

training_scores(y_train_smote, y_train_pred)
validation_scores(y_test, y_test_pred)

Training Scores:
	Accuracy = 1.0
	Precision = 1.0
	Recall = 1.0
	F1-Score = 1.0
Validation Scores:
	Accuracy = 0.886
	Precision = 0.735
	Recall = 0.864
	F1-Score = 0.795

In [81]:
from sklearn.svm import LinearSVC

svm = LinearSVC()

svm.fit(vectorized_x_train_smote, y_train_smote)

y_train_pred = svm.predict(vectorized_x_train_smote)
y_test_pred = svm.predict(vectorized_x_test)

training_scores(y_train_smote, y_train_pred)
validation_scores(y_test, y_test_pred)

Training Scores:
	Accuracy = 0.993
	Precision = 0.986
	Recall = 1.0
	F1-Score = 0.993
Validation Scores:
	Accuracy = 0.895
	Precision = 0.77
	Recall = 0.837
	F1-Score = 0.802

In [83]:
import pickle
with open ('../static/model/modle.pickle','wb') as file:
pickle.dump(lr,file)

IndentationError: expected an indented block after 'with' statement on line 2 (3370265997.py, line 3)

In [84]:
import pickle

with open('../static/model/model.pickle', 'wb') as file:
    pickle.dump(lr, file)